repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: detect-aws-credentials
        args: [--allow-missing-credentials]

- repo: https://github.com/humitos/mirrors-autoflake.git
  rev: v1.1
  hooks:
    - id: autoflake
      args: ['--in-place', '--expand-star-imports', '--remove-all-unused-imports']

-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
        args: [--line-length=120]

        #-   repo: https://github.com/pre-commit/mirrors-isort
        #    rev: v4.3.21
        #    hooks:
        #    -  id: isort
