version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7

  build:
    commands:
      - python --version
      - ./devtool build_package

  post_build:
    commands:
      - echo Running Integration tests
      - ./devtool install_deps_dev
      - ./devtool integ_tests
      - echo checking package installation
      - ./devtool install_package

artifacts:
  base-directory: dist
  files:
    - smclarify-*.whl
